### ISSUE TITLE
bundle install error

### ISSUE THREAD

**Issue by dima21m** [jbox-web/redmine_default_members#1]
C:\Bitnami\redmine-3.0.1-0\apps\redmine\htdocs>bundle install
DL is deprecated, please use Fiddle
You cannot specify the same gem twice with different version requirements.
You specified: rspec (~> 2.0) and rspec (~> 3.0.0)

**Comment by n-rodriguez** [comment]
I think you're on devel branch...
https://github.com/jbox-web/redmine_default_members/wiki/Step-by-step-installation-instructions
